version: '3.3'

services:
  database:
    image: custom-mariadb
    container_name: architekturak.database
    ports:
      - 3306:3306
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=y
      - MARIADB_DATABASE=arch
    volumes:
      - ./db_data:/var/lib/mysql
