module.exports = {
  'prefer-destructuring': 0,
  'no-dupe-class-members': 0,
  'no-extra-semi': 0,
  'no-loss-of-precision': 0,
  'no-redeclare': 0,
  'no-undef': 0, // TS-el összeakad 7.8.0 óta
  indent: 0,
  'comma-dangle': 0,
  'brace-style': 0,
  'no-unused-vars': 0,
  'lines-between-class-members': 0,
  'space-before-function-paren': 0,
  'no-extra-parens': 0,
  'no-magic-numbers': 0,
  'default-param-last': 0,
  'dot-notation': 0,
  'no-empty-function': 0,
  'no-invalid-this': 0,
  'no-loop-func': 0,
  'no-return-await': 0,
  'no-unused-expressions': 0,
  'require-await': 0,
  'no-shadow': 0,
  'no-use-before-define': 0,
  'object-curly-spacing': 0,
  camelcase: 0, // A TS naming-convention miatt ez nem kell
  'comma-spacing': 0,
  'func-call-spacing': 0,
  'keyword-spacing': 0,
  'no-array-constructor': 0,
  'no-underscore-dangle': 0,
  quotes: 0,
  semi: 0,
  'space-infix-ops': 0,
  'no-useless-constructor': 0,
  'max-params': 0
}
